<a href="https://colab.research.google.com/github/OnurcanKoken/Coursera_Machine_Learning/blob/main/Custom_Distributed_Training_TF/Week_1_Eager_Execution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np

Evaluate Tensors

In [4]:
x = 2
x_squared = tf.square(x)
print("hello, {}".format(x_squared)) # eager mode is on

hello, 4


Bradcast values

In [5]:
a = tf.constant([[1, 2], [3, 4]])
tf.add(a, 1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]], dtype=int32)>

Overload operators

In [6]:
a = tf.constant([[1, 2], [3, 4]])
a**2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  4],
       [ 9, 16]], dtype=int32)>

In [7]:
a = tf.constant(5)
b = tf.constant(3)
np.multiply(a, b)

15

Numpy interoperability

In [8]:
ndarray = np.ones([3, 3])
ndarray

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
tensor = tf.multiply(ndarray, 3)
tensor

<tf.Tensor: shape=(3, 3), dtype=float64, numpy=
array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])>

In [11]:
tensor.numpy()

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

Evaluating Variable Applications

In [12]:
v = tf.Variable(0.0)
v + 1

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [14]:
v = tf.Variable(0)
v.assign_add(1)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=1>

In [18]:
v = tf.Variable(0.0)
v.assign_add(1)
v

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.0>

In [19]:
v.read_value()

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [20]:
v.read_value().numpy()

1.0

Examine custom layers

In [21]:
class MyLayer(tf.keras.layers.Layer):
  def __init__(self):
    super(MyLayer, self).__init__()
    self.my_var = tf.Variable(100)
    self.my_other_var_list = [tf.Variable(x) for x in range(2)]

m = MyLayer()
# calls each tensor object
[variable.numpy() for variable in m.variables]

[100, 0, 1]

Change data types

In [22]:
tensor = tf.constant([1, 2, 3])
tensor

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [24]:
# cast a constant int tensor into floating point
tensor = tf.cast(tensor, dtype=tf.float32)
tensor.dtype

tf.float32