<a href="https://colab.research.google.com/github/OnurcanKoken/Coursera_Machine_Learning/blob/main/Custom_Distributed_Training_TF/Week_1_Basic_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

27.09.2021

Onurcan Köken

Coursera Custom Distributed Training with TF
Week 1

In [1]:
import tensorflow as tf

**Dense layer with a single neuron in it**

In [5]:
model = tf.keras.Sequential([tf.keras.layers.Dense(1, input_shape=(1,))])

In [3]:
# internal variables shape and datatypes
model.variables 

[<tf.Variable 'dense/kernel:0' shape=(1, 1) dtype=float32, numpy=array([[0.4590882]], dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>]


The first tf variable is named dense_1/kernel:0, and it's used to hold the weight matrix of that layer. The term kernel is another word that refers to the weights in the neural network layer.
The shape is 1, 1 so it has two dimensions. And each dimension is one unit in length. Its data type is a float 32 and it has a randomly initialized value.

The second tf variable is named dense_ /bias:0 and it stores the bias values of this layer. It has one dimension which is 1 unit in length. It's data type is also a float 32 and its initial value is zero. 

**Create your own Tensor**

**Using tf.Variable()**

In [14]:
vector = tf.Variable(initial_value=[1,2]) # default dtype=int32
vector

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>

In [15]:
vector = tf.Variable([1,2], dtype=tf.float32) # change data type as float32
vector
# vector = tf.Variable([1,2], tf.float32) # error!

<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([1., 2.], dtype=float32)>

the shape of the tensor is derived from the initial value

In [17]:
vector = tf.Variable([1, 2, 3, 4]) # shape = (4,)
vector
# vector = tf.Variable([1, 2, 3, 4], shape=(2,2)) # error! can not reshape vector to matrix

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

here is a matrix

In [12]:
vector = tf.Variable([[1,2], [3,4]]) # define it as a list of lists in the initial value
vector

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

unknown shape

In [18]:
# shape will be updated later
vector = tf.Variable([1, 2, 3, 4], shape=tf.TensorShape(None))
vector

<tf.Variable 'Variable:0' shape=<unknown> dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

string

In [20]:
mammal = tf.Variable("Elephant", dtype=tf.string)
mammal

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'Elephant'>

Complex

In [21]:
# use j as an imaginary number
its_complicated = tf.Variable(4 + 3j, dtype=tf.complex64)
its_complicated

<tf.Variable 'Variable:0' shape=() dtype=complex64, numpy=(4+3j)>

**Using tf.constant()**

NOTE THAT: You will not be able to modify the values once this tensor is created.

1-D Tensor populated with value list

In [22]:
tensor = tf.constant([1, 2, 3])
tensor

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

2-D Tensor populated with value list

In [23]:
# reshape is possible this time!
tensor = tf.constant([1, 2, 3, 4, 5, 6], shape=(2, 3)) # [1 2 3], [4 5 6]
tensor

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

2-D Tensor populated with scalar value -1

In [24]:
tensor = tf.constant(-1.0, shape=[2, 3])
tensor

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-1., -1., -1.],
       [-1., -1., -1.]], dtype=float32)>

**Math Operations with Tensors**

* tf.add
* tf.subtract
* tf.multiply
* tf.divide
* tf.div
* tf.add_n
* tf.scalar_mul
* tf.mod
* tf.abs
* tf.negative
* tf.sign
* tf.reciprocal
* tf.square
* tf.reduce_sum

ref: https://www.dummies.com/web-design-development/other-web-software/create-basic-math-operations-tensorflow/

ref2: https://www.tensorflow.org/api_docs/python/tf/math/subtract

In [28]:
tensor = tf.add([1, 2], [3, 4])
tensor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 6], dtype=int32)>

In [31]:
tf.square(5) # no dimention means it is a scalar

<tf.Tensor: shape=(), dtype=int32, numpy=25>

In [32]:
tf.reduce_sum([1, 2, 3])

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [33]:
# operator overloading, adding tensor objects
tf.square(2) + tf.square(3)

<tf.Tensor: shape=(), dtype=int32, numpy=13>

# **Basic Tensors**

In this ungraded lab, you will try some of the basic operations you can perform on tensors.

## Imports

In [34]:
try:
    # %tensorflow_version only exists in Colab.
    %tensorflow_version 2.x
except Exception:
    pass

import tensorflow as tf
import numpy as np

## Exercise on basic Tensor operations

Lets create a single dimension numpy array on which you can perform some operation. You'll make an array of size 25, holding values from 0 to 24.

In [35]:
# Create a 1D uint8 NumPy array comprising of first 25 natural numbers
x = np.arange(0, 25)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

Now that you have your 1-D array, next you'll change that array into a `tensor`. After running the code block below, take a moment to inspect the information of your tensor.

In [36]:
# Convert NumPy array to Tensor using `tf.constant`
x = tf.constant(x)
x

<tf.Tensor: shape=(25,), dtype=int64, numpy=
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])>

As the first operation to be performed, you'll square (element-wise) all the values in the tensor `x`

In [37]:
# Square the input tensor x
x = tf.square(x)
x

<tf.Tensor: shape=(25,), dtype=int64, numpy=
array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576])>

One feature of tensors is that they can be reshaped. When reshpaing, make sure you consider dimensions that will include all of the values of the tensor.

In [38]:
# Reshape tensor x into a 5 x 5 matrix. 
x = tf.reshape(x, (5, 5))
x

<tf.Tensor: shape=(5, 5), dtype=int64, numpy=
array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]])>

Notice that you'll get an error message if you choose a shape that cannot be exactly filled with the values of the given tensor.  
* Run the cell below and look at the error message
* Try to change the tuple that is passed to `shape` to avoid an error.

In [39]:
# Try this and look at the error
# Try to change the input to `shape` to avoid an error
tmp = tf.constant([1,2,3,4])
tf.reshape(tmp, shape=(2,3))

InvalidArgumentError: ignored

Like reshaping, you can also change the data type of the values within the tensor. Run the cell below to change the data type from `int` to `float`

In [40]:
# Cast tensor x into float32. Notice the change in the dtype.
x = tf.cast(x, tf.float32)
x

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[  0.,   1.,   4.,   9.,  16.],
       [ 25.,  36.,  49.,  64.,  81.],
       [100., 121., 144., 169., 196.],
       [225., 256., 289., 324., 361.],
       [400., 441., 484., 529., 576.]], dtype=float32)>

Next, you'll create a single value float tensor by the help of which you'll see `broadcasting` in action

In [41]:
# Let's define a constant and see how broadcasting works in the following cell.
y = tf.constant(2, dtype=tf.float32)
y

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

Multiply the tensors `x` and `y` together, and notice how multiplication was done and its result.

In [42]:
# Multiply tensor `x` and `y`. `y` is multiplied to each element of x.
result = tf.multiply(x, y)
result

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[   0.,    2.,    8.,   18.,   32.],
       [  50.,   72.,   98.,  128.,  162.],
       [ 200.,  242.,  288.,  338.,  392.],
       [ 450.,  512.,  578.,  648.,  722.],
       [ 800.,  882.,  968., 1058., 1152.]], dtype=float32)>

Re-Initialize `y` to a tensor having more values.

In [43]:
# Now let's define an array that matches the number of row elements in the `x` array.
y = tf.constant([1, 2, 3, 4, 5], dtype=tf.float32)
y

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([1., 2., 3., 4., 5.], dtype=float32)>

In [44]:
# Let's see first the contents of `x` again.
x

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[  0.,   1.,   4.,   9.,  16.],
       [ 25.,  36.,  49.,  64.,  81.],
       [100., 121., 144., 169., 196.],
       [225., 256., 289., 324., 361.],
       [400., 441., 484., 529., 576.]], dtype=float32)>

Add the tensors `x` and `y` together, and notice how addition was done and its result.

In [45]:
# Add tensor `x` and `y`. `y` is added element wise to each row of `x`.
result = x + y
result

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[  1.,   3.,   7.,  13.,  21.],
       [ 26.,  38.,  52.,  68.,  86.],
       [101., 123., 147., 173., 201.],
       [226., 258., 292., 328., 366.],
       [401., 443., 487., 533., 581.]], dtype=float32)>

### The shape parameter for tf.constant

When using `tf.constant()`, you can pass in a 1D array (a vector) and set the `shape` parameter to turn this vector into a multi-dimensional array.

In [46]:
tf.constant([1,2,3,4], shape=(2,2))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

### The shape parameter for tf.Variable

Note, however, that for `tf.Variable()`, the shape of the tensor is derived from the shape given by the input array.  Setting `shape` to something other than `None` will not reshape a 1D array into a multi-dimensional array, and will give a `ValueError`.

In [47]:
try:
    # This will produce a ValueError
    tf.Variable([1,2,3,4], shape=(2,2))
except ValueError as v:
    # See what the ValueError says
    print(v)

The initial value's shape ((4,)) is not compatible with the explicitly supplied `shape` argument ((2, 2)).
